[tool.pinto]
steps = [
    "datagen:deploy-background",
    "datagen:generate-waveforms",
    "datagen:deploy-timeslide-waveforms",
    "train:train:resnet",
    "export:export-model:resnet",
    "infer:deploy-infer",
    "plots:sensitive-volume",
    "plots:1D-param-hist",
    "plots:2D-param-hist"
]

[tool.typeo.base]
basedir = "${BASE_DIR}"
datadir = "${DATA_DIR}"
accounting_group_user = "${LIGO_USERNAME}"
accounting_group = "${LIGO_GROUP}"
logdir = "${BASE_DIR}/log"
sample_rate = 2048
kernel_length = 8
ifos = ['H1', 'L1']
hopeless_snr_thresh = 4
global_seed = 42

train_start = 1240579783
train_stop = 1241443783  # 10 day train window
test_stop = 1244035783 # 30 day test window

channel = "OPEN"
frame_type = "HOFT_C01"
state_flag = "DATA" # open data segments
resnet = {layers = [3, 4, 6, 3], norm_groups = 16}
resnet2d = {layers = [3, 4, 6, 3], norm_groups = 16}
repository_directory = "${BASE_DIR}/model_repo/" 
force_generation = false
Tb = 31536000  # 1 year of background
inference_sampling_rate = 4
integration_window_length = 1
inference_batch_size = 128
inference_psd_length = 64
training_psd_length = 8
trigger_distance = -0.75

waveform_duration = 8
reference_frequency = 50
minimum_frequency = 20
highpass = 32
training_prior = "aframe.priors.priors.end_o3_ratesandpops"
testing_prior = "aframe.priors.priors.end_o3_ratesandpops"
fduration = 1
valid_frac = 0.25
cosmology = "aframe.priors.cosmologies.planck"
streams_per_gpu = 3
waveform_approximant = "IMRPhenomPv2"
verbose = true


[tool.typeo.scripts.deploy-background]
datadir = "${base.datadir}"
logdir = "${base.logdir}"
channel = "${base.channel}"
state_flag = "${base.state_flag}"
train_start = "${base.train_start}" 
train_stop = "${base.train_stop}" 
test_stop = "${base.test_stop}"
ifos = "${base.ifos}"
sample_rate = "${base.sample_rate}" 
minimum_train_length = 8000
minimum_test_length = 1024
force_generation = "${base.force_generation}"
accounting_group = "${base.accounting_group}"
accounting_group_user = "${base.accounting_group_user}"

[tool.typeo.scripts.generate-glitches]
snr_thresh = 5
window = 2
start = "${base.glitch_start}"
stop = "${base.train_stop}"
test_stop = "${base.test_stop}"
channel = "${base.channel}"
frame_type = "${base.frame_type}"
state_flag = "${base.state_flag}"
f_min = "${base.highpass}"
q_min = 3.3166
q_max = 108
cluster_dt = 0.5
chunk_duration = 124
segment_duration = 64 
overlap = 4
mismatch_max = 0.2
force_generation = "${base.force_generation}"
ifos = "${base.ifos}"
datadir = "${base.datadir}/train"
logdir = "${base.logdir}"
sample_rate = "${base.sample_rate}"
analyze_testing_set = false
verbose = true

[tool.typeo.scripts.generate-waveforms]
minimum_frequency = "${base.minimum_frequency}" 
reference_frequency = "${base.reference_frequency}"
datadir = "${base.datadir}/train"
logdir = "${base.logdir}"
num_signals = 100000
prior = "${base.training_prior}"
sample_rate = "${base.sample_rate}" 
waveform_duration = "${base.waveform_duration}"
force_generation = "${base.force_generation}"
waveform_approximant = "${base.waveform_approximant}"

[tool.typeo.scripts.train]
# input and output paths
background_dir = "${base.datadir}/train/background"
waveform_dataset = "${base.datadir}/train/signals.h5"

logdir = "${base.logdir}"
outdir = "${base.basedir}/training"

# optimization args
batch_size = 384
max_epochs = 200
max_lr = 0.000585
lr_ramp_epochs = 23
weight_decay = 0.0

snr_thresh = "${base.hopeless_snr_thresh}"
max_min_snr = 12
max_snr = 100
snr_alpha = 3
snr_decay_steps = 989

# data args
ifos = "${base.ifos}"
sample_rate = "${base.sample_rate}"
kernel_length = "${base.kernel_length}"
fduration = "${base.fduration}"
highpass = "${base.highpass}"
psd_length = "${base.training_psd_length}"

# augmentation args
trigger_distance = "${base.trigger_distance}"
waveform_prob = 0.277
swap_frac = 0.014
mute_frac = 0.055

# validation args
valid_frac = "${base.valid_frac}"
valid_stride = 0.5
max_fpr = 1e-3
valid_livetime = 57600  # 16 hours of background
early_stop = 200
checkpoint_every = 3

# misc args
device = "cuda"
profile = false
use_amp = true
seed = "${base.global_seed}"

# arch parameters
commands.resnet = "${base.resnet}"

[tool.typeo.scripts.export-model]
# paths
repository_directory = "${base.repository_directory}" 
logdir = "${base.logdir}"
weights = "${base.basedir}/training/weights.pt"

# input-output mapping info
num_ifos = 2 
inference_sampling_rate = "${base.inference_sampling_rate}"
sample_rate = "${base.sample_rate}"
kernel_length = "${base.kernel_length}"
batch_size = "${base.inference_batch_size}"
fduration = "${base.fduration}"
highpass = "${base.highpass}"
psd_length = "${base.inference_psd_length}"

# repo/triton parameters
aframe_instances = 6
streams_per_gpu = "${base.streams_per_gpu}"
platform = "tensorrt_plan"
verbose = false
clean = true

# arch parameters
commands.resnet = "${base.resnet}"

[tool.typeo.scripts.deploy-timeslide-waveforms]
# paths and what not
outdir = "${base.basedir}"
datadir = "${base.datadir}"
logdir = "${base.logdir}"
accounting_group = "${base.accounting_group}"
accounting_group_user = "${base.accounting_group_user}"
seed = "${base.global_seed}"

# background parameters
start = "${base.train_stop}"
stop = "${base.test_stop}"
psd_length = "${base.inference_psd_length}"
sample_rate = "${base.sample_rate}"
ifos = "${base.ifos}"
min_segment_length = 1024

# timeslide parameters
shifts = [0, 1]
Tb = "${base.Tb}"

# injection parameters
prior = "${base.testing_prior}"
minimum_frequency = "${base.minimum_frequency}"
reference_frequency = "${base.reference_frequency}"
highpass = "${base.highpass}"
spacing = 16
buffer = 16
snr_threshold = "${base.hopeless_snr_thresh}" 
waveform_duration = "${base.waveform_duration}"
waveform_approximant = "${base.waveform_approximant}"

[tool.typeo.scripts.deploy-infer]
# paths
model_repo_dir = "${base.repository_directory}"
data_dir = "${base.datadir}/test/background"
injection_set_file = "${base.datadir}/test/waveforms.h5"
output_dir = "${base.basedir}/infer"
log_dir = "${base.logdir}"

# condor args
accounting_group_user = "${base.accounting_group_user}"
accounting_group = "${base.accounting_group}"

# triton args
model_name = "aframe-stream"
model_version = -1
image = "hermes/tritonserver:22.12"
sequence_id = 1001

# timeslide args
Tb = "${base.Tb}"
shifts = [0, 1]
throughput = 1000

# data args
sample_rate = "${base.sample_rate}"
inference_sampling_rate = "${base.inference_sampling_rate}"
batch_size = "${base.inference_batch_size}"
ifos = "${base.ifos}"
chunk_size = 4096

# analysis args
integration_window_length = "${base.integration_window_length}"
cluster_window_length = 8
fduration = "${base.fduration}"
psd_length = "${base.inference_psd_length}"

# misc
verbose = "${base.verbose}"

[tool.typeo.scripts.sensitive-volume]
background_file = "${base.basedir}/infer/background.h5"
foreground_file = "${base.basedir}/infer/foreground.h5"
rejected_params = "${base.datadir}/test/rejected-parameters.h5"
output_dir = "${base.basedir}/infer/"
log_file = "${base.basedir}/log/sensitive_volume.log"
max_far = 1000
sigma = 0.1
verbose = "${base.verbose}"

[tool.typeo.scripts.1D_param_hist]
foreground_file = "${base.basedir}/infer/foreground.h5"
rejected_params = "${base.basedir}/test/rejected-parameters.h5"
output_fname = "${base.basedir}/infer/1D_param_hist.html"
log_file = "${base.basedir}/log/1D_param_hist.log"
verbose = "${base.verbose}"

[tool.typeo.scripts.2D_param_hist]
foreground_file = "${base.basedir}/infer/foreground.h5"
rejected_params = "${base.basedir}/test/rejected-parameters.h5"
output_fname = "${base.basedir}/infer/2D_param_hist.html"
log_file = "${base.basedir}/log/2D_param_hist.log"
verbose = "${base.verbose}"

[tool.typeo.scripts.online-deployment]
outdir = "${base.basedir}"
datadir = "/dev/shm/kafka"
ifos = "${base.ifos}"
channel = "GDS-CALIB_STRAIN"
sample_rate = "${base.sample_rate}"
kernel_length = "${base.kernel_length}"
inference_sampling_rate = 512
psd_length = "${base.inference_psd_length}"
trigger_distance = "${base.trigger_distance}"
fduration = "${base.fduration}"
integration_window_length = "${base.integration_window_length}"
highpass = "${base.highpass}"
far_per_day = 1
secondary_far_threshold = 24
server = "playground"
# ifo_suffix = "O3ReplayMDC"
verbose = false

commands.resnet = "${base.resnet}"
commands.resnet2d = "${base.resnet2d}"
